### ISSUE TITLE
When I click 'install' there is timeout for mongodb

### ISSUE THREAD

**Issue by Matman94** [grandnode/grandnode2#248]
Hi,
My docker-compose.yml:

```
version: '3.3'
services:
    mongo:
        ports:
            - '127.0.0.1:27017:27017'
        container_name: mongodb
        image: mongo
    
    grandnode2:
        ports:
            - '80:80'
        container_name: grandnode2
        links:
            - 'mongodb:mongo'
        image: grandnode/grandnode2
```

I'm using this containers on my local machine (windows 10). When I fill out instalation form with 'MongoDB server name': `localhost:27017` then get timeout...

`http://localhost/install`
![image](https://user-images.githubusercontent.com/23061794/160230504-9dadc48c-b1c1-4168-b71e-d386ad17cb75.png)

![image](https://user-images.githubusercontent.com/23061794/160230518-59076777-4312-4b7b-af9f-75274d6f8bc0.png)

'QueryAssist' or my own project connects to `localhost: 27017` without any problem. 

I use your dockers with readme from github:

`https://github.com/grandnode/grandnode2`
![image](https://user-images.githubusercontent.com/23061794/160230633-adbcc232-b582-4ea1-9758-ea0e70acb913.png)
